### PR TITLE
daos: dcp: enhanced error checking

### LINKED ISSUE #361: daos: exit dcp when the source and destination are the same
1. If the DAOS source and destination container are the same, and the source and destination path are the same, then dcp should exit without trying to perform a copy. For example:
```
dcp --daos-svcl 0 --daos-src-pool $pool1 --daos-src-cont $p1cont1 --daos-dst-pool $pool1 --daos-dst-cont $p1cont1 / /
```
2. Similarly, for UNS paths:
```
dcp --daos-svcl 0  /some/uns/path  /some/uns/path
```
3. If feasible, it might also be a good idea to check if the source and destination are the same when one of them is mounted with dfuse. For example:
```
dcp --daos-svcl 0 --daos-src-pool $pool1 --daos-src-cont $p1cont1  /  /dfuse/mount/for/p1cont1
```
4. More generally, we might consider doing the same when the POSIX source and destination are the same. For example:
```
dcp  /posix/path  /posix/path
```

### LINKED ISSUE #363: daos: return copy errors in dcp
Mirrored DAOS Jira ticket: https://jira.hpdd.intel.com/browse/DAOS-5577

`dcp.c` does not return the error code from `mfu_flist_copy`.

After all of the files have been copied (either with or without errors), `rc` is set to `1` if there is an error.
https://github.com/hpc/mpifileutils/blob/b9eca8e89d41097172836cf16a938d3094e1dcbe/src/dcp/dcp.c#L651-L658

However, farther down in the DAOS cleanup, `rc` is overwritten:
https://github.com/hpc/mpifileutils/blob/b9eca8e89d41097172836cf16a938d3094e1dcbe/src/dcp/dcp.c#L678-L691

Ultimately, this means that any errors coming from `mfu_flist_copy` are not captured in `dcp.c`. These errors are still logged in the corresponding places, but `dcp.c` ignores them and potentially `return 0`, which doesn't indicate an issue has occurred.

It would be useful if `dcp.c` returned this error code from `mfu_flist_copy`. Perhaps the DAOS cleanup can use a `tmp_rc` instead of `rc`, to ovoid overwriting the value. Then, the `rc` value can be returned at the end of `dcp.c`.

### LINKED ISSUE #370: daos: dcp: improved error checking
These DAOS Jira tickets correspond to dcp.

- dcp require pool UUID when cont UUID is given
  - https://jira.hpdd.intel.com/browse/DAOS-5595
- dcp: add error codes
  - https://jira.hpdd.intel.com/browse/DAOS-5600
- dcp gracefully handle failed daos_init()
  - https://jira.hpdd.intel.com/browse/DAOS-5613
- dcp alert user when using UNS path with no svcl
  - https://jira.hpdd.intel.com/browse/DAOS-5614
- dcp make sure pool/container UUID and path exists
  - https://jira.hpdd.intel.com/browse/DAOS-5615
- dcp auto-create destination container in different pool
  - https://jira.hpdd.intel.com/browse/DAOS-5616

### PR DESCRIPTION
**Pull request by daltonbohning**
My branch deviated a bit from my previous PR, I had many small commits, and git wasn't cooperating, so I'm just creating a new PR entirely.

**common/mfu_errors.h**
- New file
- Defines some generic error codes, codes for dcp, and codes for DAOS
  - Ranges are in the 1000s, 1100s, and 4000s
- Defines MFU_ERRF and MFU_ERRP for printing the error codes.
  - Formatted as: MFU_ERR(#)
  - Could be improved in the future to print the"string" error code instead of just MFU_ERR
    - DAOS has something similar to this

**common/mfu_io**
- Defined daos_access

**common/mfu_param_path.c**
- mfu_param_path_check_copy - Return on DAOS error

**common/mfu_util**
- daos_connect
  - Added flag for whether or not to connect to pool
  - Added flag for whether or not to auto-create the destination container
    - No longer creates the source container automatically
  - These flags allow a centralized way to capture errors. I.e. only one bcast is needed for pool connection, cont connection, cont creation
  - Rank 0 now tracks and broadcasts any errors before trying to share the handles
  - Function returns an error

**dcp/dcp.c**
- Use the new error codes from mfu_error.h
- DAOS errors are generally handled more precisely
  - Each process tracks local errors, and stops making DAOS calls once it has run into an error
  - Allreduce on local DAOS errors, so all processes will know to exit
  - Check DAOS arguments before trying to make DAOS calls
  - Refactored daos_connect calls to better capture errors and exit if found
  - More gracefully handle a failed daos_init call
  - Exit if DAOS source is DAOS destination

closes #363 
closes #361
closes #370

### CODE REVIEW

**Review by dsikich — APPROVED** [review]

File: src/common/mfu_io.c [hunk 1]
```diff
@@ -227,11 +227,23 @@ int mfu_access(const char* path, int amode)
...
 {
 #ifdef DAOS_SUPPORT
-    /* noop becuase daos have an access call */
-    return 0;
+    char* name     = NULL;
+    char* dir_name = NULL;
+    parse_filename(path, &name, &dir_name);
+    assert(dir_name);
+
+    dfs_obj_t *parent = NULL;
```
Comment (adammoody) [inline src/common/mfu_io.c:238]:
```suggestion
    dfs_obj_t* parent = NULL;
```

File: src/common/mfu_util.c [hunk 2]
```diff
@@ -107,58 +107,89 @@ void daos_bcast_handle(
...
-        int rc = daos_pool_connect(pool_uuid, NULL, svcl, DAOS_PC_RW,
-                               poh, &pool_info, NULL);
-        if (rc != 0) {
-            MFU_LOG(MFU_LOG_ERR, "Failed to connect to pool");
+            daos_pool_info_t pool_info;
+            rc = daos_pool_connect(pool_uuid, NULL, svcl, DAOS_PC_RW,
+                    poh, &pool_info, NULL);
+            if (rc != 0) {
+                MFU_LOG(MFU_LOG_ERR, "Failed to connect to pool");
+                goto bcast;
```
Comment (adammoody) [inline src/common/mfu_util.c:143]: do we want a d_rank_list_free(svcl) call in here?

File: src/common/mfu_util.c [hunk 3]
```diff
@@ -107,58 +107,89 @@ void daos_bcast_handle(
...
         }
-        d_rank_list_free(svcl);
 
-        /* attempt to open the daos container */
+        /* Try to open the container */
         daos_cont_info_t co_info;
         rc = daos_cont_open(*poh, cont_uuid, DAOS_COO_RW, coh, &co_info, NULL);
-
+        
         /* If NOEXIST we create it */
```
Comment (adammoody) [inline src/common/mfu_util.c:152]: Let's pull the lines that set ``rc =`` and the corresponding ``if (rc != 0)`` statement that checks its value right beside each other without any empty lines in between.  I find that helps with long term code maintenance in avoiding someone from inserting code in between that might reuse rc before it is checked.

File: src/common/mfu_util.c [hunk 4]
```diff
@@ -107,58 +107,89 @@ void daos_bcast_handle(
...
     }
 
-    /* broadcast pool and container handles from rank 0 */
+bcast:
+    /* broadcast valid from rank 0 */
+    MPI_Bcast(&valid, 1, MPI_INT, 0, MPI_COMM_WORLD);
+
+    /* return if invalid */
+    if (valid == 0) {
+        return -1;
```
Comment (adammoody) [inline src/common/mfu_util.c:183]: The valid check to guard the handle bast looks good.  Thanks.  One other thing to check is whether we should clean up any resources that may have been allocated if we fail.  I don't know the daos api well enough to check, but I did see one call that looked to trying to free something above which would not be called in certain error cases.

File: src/dcp/dcp.c [hunk 5]
```diff
@@ -22,7 +22,120 @@
...
+
+    /* Containers are using the same pool uuid.
+     * Make sure they are also using the same svc.
+     * This is unlikely to ever happen but we can print an error just in case. */
+    if (same_pool && have_src_svc && have_dst_svc) {
+        if (strcmp(dst_svc, src_svc) != 0) {
+            if (rank == 0) {
+                MFU_LOG(MFU_LOG_ERR, "Using same pool uuid with different svcl's");
+            }
+        rc = 1;
```
Comment (adammoody) [inline src/dcp/dcp.c:122]:
```suggestion
            rc = 1;
```

File: src/dcp/dcp.c [hunk 6]
```diff
@@ -22,7 +22,120 @@
...
+        }
+    }
+
+    /* Make sure the source and destination are different */
+    if (same_cont && have_src_path && have_dst_path) {
+        if (strcmp(src_path, dst_path) == 0) {
+            if (rank == 0) {
+                 MFU_LOG(MFU_LOG_ERR, "DAOS source is DAOS destination");
+            }
+        rc = 1;
```
Comment (adammoody) [inline src/dcp/dcp.c:132]:
```suggestion
            rc = 1;
```

File: src/common/mfu_util.c (hunk 3 above)
Comment (daltonbohning) [reply src/common/mfu_util.c:152]: Ah, yes, I agree!

File: src/dcp/dcp.c [hunk 7]
```diff
@@ -470,104 +595,160 @@ int main(int argc, char** argv)
...
             same_pool = true;
         }
-    } 
+    }
 
     /* connect to DAOS source pool if uuid is valid */
-    if (mfu_src_file->type == DAOS) {
-        /* if DAOS source pool uuid is valid, then set source file type to DAOS */
-        daos_connect(rank, src_svc, src_pool_uuid, src_cont_uuid, &src_poh, &src_coh); 
+    if (!local_daos_error && mfu_src_file->type == DAOS) {
```
Comment (adammoody) [inline src/dcp/dcp.c:687]: Skimming the code, I get the impression that local_daos_error is tracking whether the calling process has seen an error, which may be independent of other processes.  Is that right?

Comment (daltonbohning) [reply src/dcp/dcp.c:687]: Correct. It is *technically possible* that some DAOS call might fail for only a single process, some of which might stem from erroneous errors. Practically speaking, most processes at the point of the broadcast into global_daos_error are *most likely* in a similar state, but to be safe in calling MPI_Finalize(), etc., it's best to make sure. 
One such out-of sync issue that could possibly arise, though unlikely, would be in our call to duns_resolve_path. 
Let's say we have 2 processes. One of them calls duns_resolve_path and succeeds. Before the other process makes the call, the UNS path is removed from the DAOS system, and then the 2nd process makes the call, and fails. Now the processes are in different states.
This is where my reasoning for "local_daos_error" comes from, among other erroneous network errors that might crop up.

Comment (adammoody) [reply src/dcp/dcp.c:687]: Assuming that's the case, one thing to be careful of is mixed error conditions, like if local_daos_error=true on rank=0, but false on rank=1.  It looks like daos_connect includes a collective (bcast), but then you might have rank 0 skipping that call while rank 1 does.

File: src/common/mfu_util.c (hunk 4 above)
Comment (daltonbohning) [reply src/common/mfu_util.c:183]: Yes, you are right. I missed that. Thank you!

File: src/dcp/dcp.c (hunk 7 above)
Comment (adammoody) [reply src/dcp/dcp.c:687]: > 
> 
> Correct. It is _technically possible_ that some DAOS call might fail for only a single process, some of which might stem from erroneous errors. Practically speaking, most processes at the point of the broadcast into global_daos_error are _most likely_ in a similar state, but to be safe in calling MPI_Finalize(), etc., it's best to make sure.
> One such out-of sync issue that could possibly arise, though unlikely, would be in our call to duns_resolve_path.
> Let's say we have 2 processes. One of them calls duns_resolve_path and succeeds. Before the other process makes the call, the UNS path is removed from the DAOS system, and then the 2nd process makes the call, and fails. Now the processes are in different states.
> Another such issue might be with mounting, since we could possibly run out of mountpoints for only one process.
> This is where my reasoning for "local_daos_error" comes from, among other erroneous network errors that might crop up.

Makes sense.  Good thinking.

Comment (daltonbohning) [reply src/dcp/dcp.c:687]: Oh yes... I'll need to rework that portion.

**Comment by daltonbohning** [comment]
Thanks for all the input @adammoody !
I should have these things all resolved tomorrow.

File: src/dcp/dcp.c (hunk 7 above)
Comment (adammoody) [reply src/dcp/dcp.c:687]: This kind of check comes up a lot.  This utility function comes in handy:
https://github.com/hpc/mpifileutils/blob/a9cd09d6a4412b5a5e87419c8423d6d79f32caab/src/common/mfu_util.c#L1096

You can use it like `` if (! mfu_alltrue(fd >= 0, MPI_COMM_WORLD)) ``

File: src/common/mfu_util.c (hunk 4 above)
Comment (daltonbohning) [reply src/common/mfu_util.c:183]: Luckily, I think only the d_rank_list_free was missing here, since the pool/container handles are declared statically as structs in dcp.c, and the daos calls expect them to not be NULL, so I don't believe the daos calls allocate anything else here.

File: src/common/mfu_util.c (hunk 2 above)
Comment (daltonbohning) [reply src/common/mfu_util.c:143]: Yes, good catch!

File: src/dcp/dcp.c (hunk 7 above)
Comment (daltonbohning) [reply src/dcp/dcp.c:687]: This is the full function:
https://github.com/daltonbohning/mpifileutils/blob/6f4a6d3252b720c770ed2bcb64c99dac3ae9f2bf/src/common/mfu_util.c#L1125-L1133

Then, I would use it like `if ! (mfu_alltrue(!local_daos_error, MPI_COMM_WORLD))`

But this function uses `MPI_INT`, `MPI_LAND`, whereas mine was using `MPI_C_BOOL`, `MPI_LOR`.
Do you know if there would be any performance difference here? I.e. perhaps MPI has an optimized implementation for `MPI_C_BOOL`, `MPI_LOR` vs `MPI_INT`, `MPI_LAND`?

Comment (daltonbohning) [reply src/dcp/dcp.c:687]: I actually found another hole in the logic here, where `same_pool` could potentially be mixed if a process has an error, and so the daos_connect call might be mixed. I ended up putting another reduction on `local_daos_error` before calling `daos_connect`. Even if refactored, I couldn't think of another way around this that was foolproof.

**Comment by daltonbohning** [comment]
I made some style updates, corrected the "hole" with the way `local_daos_error` and `daos_connect` were being handled, and also corrected another hole with `local_daos_error` and `same_pool`.

File: src/dcp/dcp.c (hunk 7 above)
Comment (adammoody) [reply src/dcp/dcp.c:717]: > 
> 
> This is the full function:
> https://github.com/daltonbohning/mpifileutils/blob/6f4a6d3252b720c770ed2bcb64c99dac3ae9f2bf/src/common/mfu_util.c#L1125-L1133
> 
> Then, I would use it like `if ! (mfu_alltrue(!local_daos_error, MPI_COMM_WORLD))`
> 
> But this function uses `MPI_INT`, `MPI_LAND`, whereas mine was using `MPI_C_BOOL`, `MPI_LOR`.
> Do you know if there would be any performance difference here? I.e. perhaps MPI has an optimized implementation for `MPI_C_BOOL`, `MPI_LOR` vs `MPI_INT`, `MPI_LAND`?
> Or even just a difference between only the datatypes? Or only the `LAND` vs `LOR`? _**Theoretically**_, `MPI_C_BOOL`, `MPI_LOR` _**could**_ be implemented in a more efficient manner.

Yes, that's right.  One could implement an LAND/LOR allreduce on a bool using a single bit versus the 32-bits an int type would require.  It should be fine to modify the mfu_alltrue function to take a bool as its input if you're up for it.

Comment (daltonbohning) [reply src/dcp/dcp.c:717]: Sure, I'll do that (after a quick sanity check to everything calling mfu_alltrue).

File: src/dcp/dcp.c [hunk 8]
```diff
@@ -496,76 +711,68 @@ int main(int argc, char** argv)
...
+    /* If the source and destination are in the same pool,
+     * then open the container in that pool.
+     * Otherwise, connect to the second pool and open the container */
+    if (!local_daos_error && mfu_dst_file->type == DAOS) {
+        if (same_pool) {
+            /* Don't reconnect to pool, but do create container if non-existent */
+            if (rank == 0)
+                rc = daos_connect(rank, dst_svc, dst_pool_uuid, dst_cont_uuid, &src_poh, &dst_coh, false, true);
+            else
+                rc = daos_connect(rank, dst_svc, dst_pool_uuid, dst_cont_uuid, &src_poh, &dst_coh, false, true);
```
Comment (adammoody) [inline src/dcp/dcp.c:735]: Just another style thing is that we brace even one-line code blocks, again to avoid future bugs sneaking in where someone later adds a second line in the block without realizing the braces are missing.
```suggestion
            if (rank == 0) {
                rc = daos_connect(rank, dst_svc, dst_pool_uuid, dst_cont_uuid, &src_poh, &dst_coh, false, true);
            } else {
                rc = daos_connect(rank, dst_svc, dst_pool_uuid, dst_cont_uuid, &src_poh, &dst_coh, false, true);
            }
```

Comment (daltonbohning) [reply src/dcp/dcp.c:735]: This one is interesting... That was a quick debug I was doing, but then removed it. There should only be a singel `daos_connect` call there, and my local branch has the correct version...
I'm investigating now to see why git ignored these changes...

**Comment by adammoody** [comment]
@daltonbohning , thanks for checking those other return code cases.  I made one more style request, but otherwise it looks good to me.

The DAOS code that leads into the tool is getting long enough that we can think about abstracting that into a function (starting at line 632 in dcp.c).  That can be done later, though.

File: src/dcp/dcp.c (hunk 8 above)
Comment (daltonbohning) [reply src/dcp/dcp.c]: Okay this was very strange. My local repo was "up to date", but still did not match the branch on GitHub.
Anyway, I fixed it. Thanks for the catch!

**Comment by daltonbohning** [comment]
@adammoody You're welcome, but really, thank you for catching this! Another set of eyes definitely helps.
I've had a similar thought about abstracting the daos-specific code. I'll go ahead and make an issue to keep track of this, and I'll make those changes when I get a chance, especially since we will be making more daos changes and additions in the future.

I pushed a couple more things in the last few minutes. If you don't find anything else, I don't have anything more to add to this PR.

**Comment by adammoody** [comment]
No problem.  Those MPI corner cases can be tricky.

Thanks, @daltonbohning .  Looks good to me.  Would you mind squashing those commits into one and force pushing back?

**Comment by adammoody** [comment]
Oh, you can leave the mfu_alltrue commit separate in the squash since that's a different fix.

**Comment by daltonbohning** [comment]
Sorry, I'm working on this. My repo seemed to have a breakdown and it's taking a lot of time to squash these commits.
(It explains the strange out-of-sync issue I ran into earlier)
